package patches.projects

import jetbrains.buildServer.configs.kotlin.*
import jetbrains.buildServer.configs.kotlin.Project
import jetbrains.buildServer.configs.kotlin.projectFeatures.kubernetesConnection
import jetbrains.buildServer.configs.kotlin.ui.*

/*
This patch script was generated by TeamCity on settings change in UI.
To apply the patch, change the root project
accordingly, and delete the patch script.
*/
changeProject(DslContext.projectId) {
    features {
        add {
            kubernetesConnection {
                id = "PROJECT_EXT_13"
                name = "k8s-eqx / agents-jbr-fed"
                apiServerUrl = "https://eqx.k8s.intellij.net:6443"
                caCertificate = "credentialsJSON:e3d2e14e-fade-49de-a8d0-89b5ebe305e0"
                namespace = "agents-jbr-fed"
                authStrategy = token {
                    token = "credentialsJSON:e425f8e7-fe04-40b8-b5bc-b35f38405e35"
                }
            }
        }
    }
}
