package patches.projects

import jetbrains.buildServer.configs.kotlin.*
import jetbrains.buildServer.configs.kotlin.Project
import jetbrains.buildServer.configs.kotlin.projectFeatures.UntrustedBuildsSettings
import jetbrains.buildServer.configs.kotlin.projectFeatures.untrustedBuildsSettings
import jetbrains.buildServer.configs.kotlin.ui.*

/*
This patch script was generated by TeamCity on settings change in UI.
To apply the patch, change the root project
accordingly, and delete the patch script.
*/
changeProject(DslContext.projectId) {
    features {
        add {
            untrustedBuildsSettings {
                id = "PROJECT_EXT_22"
                defaultAction = UntrustedBuildsSettings.DefaultAction.APPROVE
                enableLog = false
                approvalRules = "user:evgeny.grigorenko@jetbrains.com"
            }
        }
    }
}
