"""DP-FTRL integration for PyTorch.

Provides two ways to use DP-FTRL (correlated noise mechanisms):

1. **Composable transform (recommended)**: Use the ``Privatizer`` from
   ``opaque.noise.matrix_factorization`` directly in your training loop.
   This follows the JAX-Privacy / TorchOpt philosophy of composable
   transforms rather than optimizer wrappers::

       privatizer = matrix_factorization_privatizer(noising, stddev=...)
       noise_state = privatizer.init(grad_template)
       optimizer = torch.optim.SGD(model.parameters(), lr=0.01)

       for batch in dataloader:
           clipped_grad = ...  # per-example clipping
           noisy_grad, noise_state = privatizer.update(clipped_grad, noise_state)
           assign_grads(model, noisy_grad)
           optimizer.step()

2. **Convenience wrapper**: ``DPFTRLOptimizer`` wraps a base optimizer for
   simpler integration when you don't need full composability.

The ``dp_ftrl_train_step`` function provides a composable single-step
helper that combines noise addition with an optimizer update.

References:
    - DP-FTRL: https://arxiv.org/abs/2103.00039
    - BandMF: https://arxiv.org/abs/2306.08153
    - BLT: https://arxiv.org/abs/2404.16706
"""

from __future__ import annotations

import dataclasses
from collections.abc import Callable
from typing import Any

import torch

from opaque.matrix_factorization import streaming_matrix
from opaque.noise.matrix_factorization import (
    Privatizer,
    PrivatizerState,
    matrix_factorization_privatizer,
)


def dp_ftrl_train_step(
    clipped_grads: Any,
    noise_state: PrivatizerState,
    privatizer: Privatizer,
    params: list[torch.Tensor],
    optimizer: torch.optim.Optimizer,
) -> tuple[PrivatizerState, list[torch.Tensor]]:
    """Composable single training step for DP-FTRL.

    Applies correlated noise to clipped gradients, writes them to parameter
    ``.grad`` fields, and runs the optimizer. This is the recommended
    functional API for integrating DP-FTRL into custom training loops.

    Args:
        clipped_grads: Clipped gradient pytree (dict, list, or tensor).
        noise_state: Current privatizer state.
        privatizer: The noise-addition privatizer.
        params: List of model parameters (in the same order as clipped_grads).
        optimizer: Any PyTorch optimizer.

    Returns:
        Tuple of (new_noise_state, updated_params).

    Example::

        from opaque.noise.matrix_factorization import matrix_factorization_privatizer
        from opaque.dp_ftrl import dp_ftrl_train_step

        privatizer = matrix_factorization_privatizer(noising, stddev=sigma)
        noise_state = privatizer.init(grad_template)
        optimizer = torch.optim.SGD(model.parameters(), lr=0.01)

        for batch in dataloader:
            clipped_grad = compute_clipped_grad(model, batch)
            noise_state, _ = dp_ftrl_train_step(
                clipped_grad, noise_state, privatizer,
                list(model.parameters()), optimizer,
            )
    """
    noisy_grads, new_noise_state = privatizer.update(clipped_grads, noise_state)

    # Write noisy gradients to parameter .grad
    if isinstance(noisy_grads, dict):
        for i, p in enumerate(params):
            p.grad = noisy_grads[i].to(p.dtype)
    elif isinstance(noisy_grads, (list, tuple)):
        for p, g in zip(params, noisy_grads, strict=True):
            p.grad = g.to(p.dtype)
    elif isinstance(noisy_grads, torch.Tensor):
        # Single-param case
        params[0].grad = noisy_grads.to(params[0].dtype)
    else:
        # General pytree — flatten and assign
        import optree

        flat_grads = optree.tree_leaves(noisy_grads)
        for p, g in zip(params, flat_grads, strict=True):
            p.grad = g.to(p.dtype)

    with torch.no_grad():
        optimizer.step()

    return new_noise_state, list(params)


@dataclasses.dataclass
class DPFTRLState:
    """State for DP-FTRL optimizer.

    Attributes:
        privatizer_state: State of the noise-addition privatizer.
        step: Current training step.
    """

    privatizer_state: PrivatizerState
    step: int = 0


class DPFTRLOptimizer:
    """Convenience DP-FTRL optimizer wrapping a base PyTorch optimizer.

    For maximum composability, prefer using the ``Privatizer`` directly
    or ``dp_ftrl_train_step``. This wrapper is provided for simpler
    integration when composability is not needed.

    This optimizer adds correlated noise to gradients before applying the
    base optimizer update. The noise is generated by a streaming matrix
    factorization mechanism.

    Args:
        params: Model parameters (iterable of tensors or param groups).
        noising_matrix: A ``StreamingMatrix`` or dense ``Tensor`` representing
            C^{-1}. Determines the noise correlation structure.
        base_optimizer_cls: Base PyTorch optimizer class (e.g., ``torch.optim.SGD``).
        lr: Learning rate for the base optimizer.
        stddev: Standard deviation for the base noise.
        seed: Optional random seed for reproducible noise.
        noise_dtype: Optional dtype for noise computation.
        **base_optimizer_kwargs: Additional kwargs for the base optimizer.
    """

    def __init__(
        self,
        params,
        noising_matrix: torch.Tensor | streaming_matrix.StreamingMatrix,
        base_optimizer_cls: type[torch.optim.Optimizer],
        lr: float,
        stddev: float,
        seed: int | None = None,
        noise_dtype: torch.dtype | None = None,
        **base_optimizer_kwargs,
    ):
        self._params = list(params)
        self._base_optimizer = base_optimizer_cls(
            self._params, lr=lr, **base_optimizer_kwargs
        )
        self._privatizer = matrix_factorization_privatizer(
            noising_matrix, stddev=stddev, seed=seed, dtype=noise_dtype
        )

        template = {i: torch.zeros_like(p) for i, p in enumerate(self._params)}
        self._dp_state = DPFTRLState(
            privatizer_state=self._privatizer.init(template),
        )

    @torch.no_grad()
    def step(self, closure: Callable | None = None) -> torch.Tensor | None:
        """Perform a single DP-FTRL optimization step.

        1. Collect current gradients (assumed to be clipped).
        2. Add correlated noise via the privatizer.
        3. Apply the base optimizer update with noisy gradients.

        Args:
            closure: Optional closure that recomputes the loss.

        Returns:
            Loss value if closure is provided, else None.
        """
        loss = None
        if closure is not None:
            with torch.enable_grad():
                loss = closure()

        grads = {}
        for i, p in enumerate(self._params):
            grads[i] = p.grad.clone() if p.grad is not None else torch.zeros_like(p)

        noisy_grads, new_priv_state = self._privatizer.update(
            grads, self._dp_state.privatizer_state
        )
        self._dp_state = DPFTRLState(
            privatizer_state=new_priv_state,
            step=self._dp_state.step + 1,
        )

        for i, p in enumerate(self._params):
            p.grad = noisy_grads[i].to(p.dtype)
        self._base_optimizer.step()

        return loss

    def zero_grad(self, set_to_none: bool = True) -> None:
        """Clear gradients of all optimized parameters."""
        self._base_optimizer.zero_grad(set_to_none=set_to_none)

    @property
    def state(self) -> DPFTRLState:
        """Current DP-FTRL state."""
        return self._dp_state

    @property
    def current_step(self) -> int:
        """Current training step count."""
        return self._dp_state.step

    @property
    def param_groups(self) -> list:
        """Base optimizer param groups (for LR scheduling etc.)."""
        return self._base_optimizer.param_groups

    def state_dict(self) -> dict:
        """Return the base optimizer state dict."""
        return self._base_optimizer.state_dict()

    def load_state_dict(self, state_dict: dict) -> None:
        """Load the base optimizer state dict."""
        self._base_optimizer.load_state_dict(state_dict)
